### ISSUE TITLE
打包很多报错

### ISSUE THREAD

**Issue by luocong2016** [evolify/react-mobx-ts-antd#3]
都是react-dom的打包错误信息, 页面也是
![image](https://user-images.githubusercontent.com/25705196/39027465-9ae56fbc-4484-11e8-8c4b-1cbad9bef0a4.png)

页面

![image](https://user-images.githubusercontent.com/25705196/39027636-6e14bfb4-4485-11e8-8b52-5bc4bdea2788.png)

**Comment by evolify** [comment]
Please update your code.
