### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by picnic-yu** [evolify/react-mobx-ts-antd#4]
ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/App.tsx' is not u                                                                                                                                                                                               nder 'rootDir' '/'. 'rootDir' is expected to contain all source files.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/model/index.ts' i                                                                                                                                                                                               s not under 'rootDir' '/'. 'rootDir' is expected to contain all source files.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/model/user.ts' is                                                                                                                                                                                                not under 'rootDir' '/'. 'rootDir' is expected to contain all source files.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/Index.tsx' i                                                                                                                                                                                               s not under 'rootDir' '/'. 'rootDir' is expected to contain all source files.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/category/Cat                                                                                                                                                                                               egory.tsx' is not under 'rootDir' '/'. 'rootDir' is expected to contain all sour                                                                                                                                                                                               ce files.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/goods/Goods.                                                                                                                                                                                               tsx' is not under 'rootDir' '/'. 'rootDir' is expected to contain all source fil                                                                                                                                                                                               es.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/index/Index.                                                                                                                                                                                               tsx' is not under 'rootDir' '/'. 'rootDir' is expected to contain all source fil                                                                                                                                                                                               es.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/order/Order.                                                                                                                                                                                               tsx' is not under 'rootDir' '/'. 'rootDir' is expected to contain all source fil                                                                                                                                                                                               es.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/public/Login                                                                                                                                                                                               .tsx' is not under 'rootDir' '/'. 'rootDir' is expected to contain all source fi                                                                                                                                                                                               les.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/public/Searc                                                                                                                                                                                               hBox.tsx' is not under 'rootDir' '/'. 'rootDir' is expected to contain all sourc                                                                                                                                                                                               e files.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/src/view/user/User.ts                                                                                                                                                                                               x' is not under 'rootDir' '/'. 'rootDir' is expected to contain all source files                                                                                                                                                                                               .

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/webpack.config.js' is                                                                                                                                                                                                not under 'rootDir' '/'. 'rootDir' is expected to contain all source files.

ERROR in D:\work\crud\react-mobx-ts-antd-master\tsconfig.json
[tsl] ERROR
      TS6059: File 'D:/work/crud/react-mobx-ts-antd-master/webpack.dev.config.js                                                                                                                                                                                               ' is not under 'rootDir' '/'. 'rootDir' is expected to contain all source files.

**Comment by evolify** [comment]
你改一下tsconfig里面的rootDir配置看看，之前的版本里面我配置的是src，升级后也报错和你这类似，你现在把这个配置注释掉或者改成src试试看？
